---

prod:
  eu-west-1:
    module.barak_poc_ecr_docker_image:
      source: '"git::https://github.com/mathspace/terraform-aws-ecr-docker-image.git"'
      image_name: '"barak_poc_get_hello_world"'
      source_path: '"${path.module}/"'