---

prod:
  eu-west-1:
    resource.aws_iam_role_policy.barak_poc_ec2_policy:
      name: '"barak_poc_ec2_policy"'
      role: aws_iam_role.barak_poc_ec2_exec.id
      policy: file("configs/aws/files/policy/barak_poc_ec2_policy.json")