---

prod:
  eu-west-1:
    resource.aws_api_gateway_method.barak_poc_get_time:
      rest_api_id: aws_api_gateway_rest_api.barak_poc.id
      resource_id: aws_api_gateway_resource.barak_poc_get_time.id
      http_method: '"GET"'
      authorization: '"NONE"'

    resource.aws_api_gateway_method.barak_poc_get_hello_world:
      rest_api_id: aws_api_gateway_rest_api.barak_poc.id
      resource_id: aws_api_gateway_resource.barak_poc_get_hello_world.id
      http_method: '"GET"'
      authorization: '"NONE"'